- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Expense Configuration file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Add Pre-requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted

- name: Newrelic monitoring for nginx
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash &&  NEW_RELIC_API_KEY="{{ lookup( 'amazon.aws.aws_ssm', 'expense.newrelic.key', region='us-east-1' ) }}" NEW_RELIC_ACCOUNT_ID={{ lookup( 'amazon.aws.aws_ssm', 'expense.newrelic.account', region='us-east-1' ) }} /usr/local/bin/newrelic install -y


