- name: Remove existing app content
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: Create Application directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory
    owner: "{{app_user}}"

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: true
